from pydantic import BaseModel
from typing import Optional
from datetime import datetime

class KBDocument(BaseModel):
    id: Optional[str] = None  # Optional, generated by database
    title: str  # Should be a string, not UUID
    content: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

    class Config:
        from_attributes = True  # Allows creation from dict/database records

class KBDocumentChunk(BaseModel):
    id: Optional[str] = None  # Optional, generated by database
    document_id: str  # Required - the parent document's ID
    chunk_index: int
    content: str
    token_count: Optional[int] = 0
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

class Config:
    from_attributes = True